// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/xxx/projects/gulfstream/pkg/stream/storage.go

// Package mockstream is a generated GoMock package.
package mockstream

import (
	context "context"
	stream "github.com/go-gulfstream/gulfstream/pkg/stream"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	reflect "reflect"
)

// MockStorage is a mock of Storage interface
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// StreamName mocks base method
func (m *MockStorage) StreamName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamName")
	ret0, _ := ret[0].(string)
	return ret0
}

// StreamName indicates an expected call of StreamName
func (mr *MockStorageMockRecorder) StreamName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamName", reflect.TypeOf((*MockStorage)(nil).StreamName))
}

// NewStream mocks base method
func (m *MockStorage) NewStream() *stream.Stream {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewStream")
	ret0, _ := ret[0].(*stream.Stream)
	return ret0
}

// NewStream indicates an expected call of NewStream
func (mr *MockStorageMockRecorder) NewStream() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewStream", reflect.TypeOf((*MockStorage)(nil).NewStream))
}

// Persist mocks base method
func (m *MockStorage) Persist(ctx context.Context, s *stream.Stream) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Persist", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Persist indicates an expected call of Persist
func (mr *MockStorageMockRecorder) Persist(ctx, s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Persist", reflect.TypeOf((*MockStorage)(nil).Persist), ctx, s)
}

// Load mocks base method
func (m *MockStorage) Load(ctx context.Context, streamID uuid.UUID) (*stream.Stream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, streamID)
	ret0, _ := ret[0].(*stream.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load
func (mr *MockStorageMockRecorder) Load(ctx, streamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockStorage)(nil).Load), ctx, streamID)
}
